### ISSUE TITLE
Rename E164Number to DTMFNumber

### ISSUE THREAD

**Issue by seanturner** [stirwg/certificates#4]
On list it was suggested that possibly E164Numbrer should be renamed to DTMFNumber because now the possible characters in the string include # and *.

**Comment by russhousley** [comment]
It seems that E164Number and DTMFNumber have connotations that we do not really want.

I suggest:

    TNAuthorizationList ::= SEQUENCE SIZE (1..MAX) OF TNEntry

    TNEntry ::= CHOICE {
      spc   [0] ServiceProviderCode,
      range [1] TelephoneNumberRange,
      one       TelephoneNumber }

    ServiceProviderCode ::= IA5String

    TelephoneNumberRange ::= SEQUENCE {
      start TelephoneNumber,
      count INTEGER (2..MAX)  }

    TelephoneNumber ::= IA5String (SIZE (1..15)) (FROM ("0123456789#*”))

**Comment by seanturner** [comment]
Note that the above is a result of further list discussion.
